### ISSUE TITLE
helpers-namespace=2017.11.11 breaks pytest-4.1.0

### ISSUE THREAD

**Issue by jbarlow83** [saltstack/pytest-helpers-namespace#7]
It seems that pytest-helpers-namespace is not compatible with pytest-4.1.0.

Downgrading to pytest-4.0.1 fixes the issue, without modifying the tests in question.

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "<PROJECT>/.venv/lib/python3.7/site-packages/_pytest/main.py", line 203, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "<PROJECT>/.venv/lib/python3.7/site-packages/_pytest/main.py", line 242, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "<PROJECT>/.venv/lib/python3.7/site-packages/pluggy/hooks.py", line 258, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "<PROJECT>/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "<PROJECT>/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "<PROJECT>/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "<PROJECT>/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "<PROJECT>/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "<PROJECT>/.venv/lib/python3.7/site-packages/_pytest/main.py", line 252, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "<PROJECT>/.venv/lib/python3.7/site-packages/_pytest/main.py", line 466, in perform_collect
INTERNALERROR>     self.config.pluginmanager.check_pending()
INTERNALERROR>   File "<PROJECT>/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 241, in check_pending
INTERNALERROR>     (name, hookimpl.plugin))
INTERNALERROR> pluggy.manager.PluginValidationError: unknown hook 'pytest_namespace' in plugin <module 'pytest_helpers_namespace.plugin' from '<PROJECT>/.venv/lib/python3.7/site-packages/pytest_helpers_namespace/plugin.py'>

**Comment by s0undt3ch** [comment]
This has been fixed in the latest release
